using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;
public class CardManager : MonoBehaviour
{
    /// <singletone>
    static public CardManager instance = null;
    /// <singletone>

    public DeckContainer deckContainer;

    public List<UnitStatus> allUnitStatus = new List<UnitStatus>();
    public List<UnitStatus> unitStatusList = new List<UnitStatus>();

    List<GameObject> AllCard = new List<GameObject>();
    int AllCardLengh;
    public GameObject[] myCard = new GameObject[8];

    public GameObject cardPrefab;
    public GameObject allCardPos;
    public GameObject myCardPos;

    public GameObject uiCanvas;

    private void Awake()
    {
        if (instance == null)
        {
            instance = this;
        }
    }

    void Start()
    {
        unitStatusList = allUnitStatus;
        for (int i = 0; i < unitStatusList.Count; i++) // Ã³ï¿½ï¿½ ï¿½ï¿½ï¿½Û¶ï¿½ ï¿½ï¿½ï¿½Ä«ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ Ç¥ï¿½ï¿½
        {
            AllCard.Add(Instantiate(cardPrefab, uiCanvas.transform));
            AllCard[i].GetComponent<CardPrefab>().status = ScriptableObject.CreateInstance<UnitStatus>();
            AllCard[i].GetComponent<CardPrefab>().status.DeepCopy(unitStatusList[i]);
            SortCard(AllCard[i], allCardPos, i);
        }
        AllCardLengh = AllCard.Count;
    }

    void Update()
    {
        if (Input.GetMouseButtonDown(1))   //Save(ï¿½ï¿½ Å»ï¿½ï¿½ï¿½Ò¶ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ë¹° ï¿½ï¿½ï¿½ï¿½ï¿½Å³ï¿½ï¿?
        {
                GameManager.MyHandsList.Clear();
            for (int i = 0; i < myCard.Length; i++)
            {
                if (myCard[i] != null)
                {
                    GameManager.MyHandsList.Add(myCard[i].GetComponent<CardPrefab>().status);
                }
            }
            SceneManager.LoadScene(0);
        }

        for (int i = 0; i < AllCard.Count; i++)
        {
            if (AllCard[i] != null)
            {
                if (AllCard[i].GetComponent<CardPrefab>().isSelect == true)
                {
                    AllCard[i].GetComponent<CardPrefab>().isSelect = false;
                    AllCardToMyCard(i);
                }
            }
        }
        for (int i = 0; i < myCard.Length; i++)
        {
            if (myCard[i] != null)
            {
                if (myCard[i].GetComponent<CardPrefab>().isSelect == true)
                {
                    print("ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ Ä«ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½: " + myCard[i].GetComponent<CardPrefab>().unitName.text);
                    myCard[i].GetComponent<CardPrefab>().isSelect = false;
                    MyCardToAllCard(i);
                }
            }
        }
        //print(AllCard.Count);
    }

    void AllCardToMyCard(int clickedCardNum)
    {
        bool swt = false;
        for (int i = 0; i < myCard.Length; i++)
        {
            if (myCard[i] == null)
            {
                if (swt == false)
                {
                    myCard[i] = AllCard[clickedCardNum]; // ï¿½ÌºÎºï¿½ myCard[?]ï¿½ï¿½ ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ Ã£ï¿½Æ¼ï¿½ ï¿½Ö¾ï¿½ï¿½Ö°ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿? AllCard[?]ï¿½ï¿½ Å¬ï¿½ï¿½ï¿½ï¿½ Ä«ï¿½å¸¦ ï¿½Î½ï¿½ï¿½Ø¼ï¿½ ï¿½Ö¾ï¿½ï¿½Ö±ï¿½
                    SortCard(myCard[i], myCardPos, i);
                    swt = true;
                }
            }
        }
        swt = false;
        AllCard.RemoveAt(clickedCardNum); //AllCard[?]ï¿½ï¿½ Å¬ï¿½ï¿½ï¿½ï¿½ Ä«ï¿½å¸¦ ï¿½Î½ï¿½ï¿½Ø¼ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½Ö±ï¿½
        for (int i = 0; i < AllCard.Count; i++)
        {
            SortCard(AllCard[i], allCardPos, i);
        }
    }

    void MyCardToAllCard(int clickedCardNum)
    {
        AllCard.Add(myCard[clickedCardNum]);
        myCard[clickedCardNum] = null;
        SortCard(AllCard[AllCard.Count - 1], allCardPos, AllCard.Count - 1);
    }


    void SortCard(GameObject gameObject, GameObject deckPos ,int cardNum) //Ä«ï¿½ï¿½ï¿½ï¿½ï¿? ï¿½ï¿½Ã¼Ä«ï¿½ï¿½orï¿½Úµï¿½, ï¿½ï¿½ï¿½Â?ï¿½ï¿½Ä¡ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
    {
        RectTransform CardRt = gameObject.GetComponent<RectTransform>();
        CardRt.anchoredPosition = SortCardVec(deckPos, cardNum);
    }

    Vector2 SortCardVec(GameObject Pos, int i)
    {
        int num = i + 1;
        int w = 0;
        int h = Mathf.Abs(i / 4);
        if (num > 4)
        {
            w = num - 4 * h;
        }
        else
        {
            w = num;
        }
        Vector2 result = Pos.GetComponent<RectTransform>().anchoredPosition + new Vector2(w * 260 - 260, 0 - h * 390);
        return result;
    }




    //unitStatusList = allUnitStatus;
    //    myCard = new GameObject[unitStatusList.Count];
    //    for (int i = 0; i<myCard.Length; i++)
    //    {
    //        myCard[i] = Instantiate(cardPrefab, uiCanvas.transform);
    //myCard[i].GetComponent<CardPrefab>().status = ScriptableObject.CreateInstance<UnitStatus>();
    //        myCard[i].GetComponent<CardPrefab>().status.DeepCopy(unitStatusList[i]);
    //        SortCard(myCard[i], i);




    //    myCard[0] = AllCard[0]; // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½Ã¼Ä«ï¿½ï¿½ï¿?ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½Ì°ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½Ù²ã¼­ ï¿½Ö±ï¿½
    //            AllCard.RemoveAt(0);
    //            for (int i = 0; i<AllCard.Count; i++)
    //            {
    //                SortCard(AllCard[i], allCardPos, i); //AllCard.Lengh ï¿½ï¿½ ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½Ö±ï¿½
    //}
    //SortCard(myCard[0], myCardPos, 0);

}


